### ISSUE TITLE
Crawler console

### ISSUE THREAD

**Issue by timrobertson100** [gbif/management-tools#1]
Port the [existing implementation](https://github.com/gbif/crawler/tree/master/crawler-ws/src/main/webapp) of crawler.gbif.org into this project.

Note that a bug exists whereby rows that are removed server side are not removed client side.  The polling mechanism should detect this and remove those rows.

**Comment by MattBlissett** [comment]
I think an extra column, showing the count (metrics/SOLR), would also be useful. That gives some idea how long something might take to complete.

**Comment by MattBlissett** [comment]
https://management-tools.gbif.org/crawling-monitor

Is there any reason not to redirect the old one?

**Comment by MortenHofft** [comment]
might be nice to keep the old for reference in case you miss a functionality?

**Comment by timrobertson100** [comment]
Thanks - yes should redirect but no need to remove from crawler project so we can always refer back internally if need be.
