### ISSUE TITLE
Highlight things crawled during last 24 hrs - or similar

### ISSUE THREAD

**Issue by timrobertson100** [gbif/management-tools#14]
The overcrawl monitor makes things look pretty bad today:

https://www.dropbox.com/s/rqqm9b2lwd0wn18/Screenshot%202017-12-23%2009.00.36.png?dl=0

But in reality the ones showing e.g. 5M were actually just caught mid-crawl.

It would be good to somehow filter those out from this view - ideally in the backend, but perhaps a front end fix could do the same.  Something that is able to basically hide them to stop administrators being distracted with something looking like it needs attention when it does not.

**Comment by MattBlissett** [comment]
Overcrawl monitor is obsolete.
