### ISSUE TITLE
IPT count = Events vs GBIF count = occurrences

### ISSUE THREAD

**Issue by peterdesmet** [gbif/management-tools#15]
The IPT count for sampling-event datasets shows the number of **Events**, while the GBIF counts shows the number of **Occurrences**, indicating in a red a difference between the two (247 vs 1553):

<img width="705" alt="ipt-count" src="https://user-images.githubusercontent.com/600993/35725922-690022c0-0803-11e8-8df4-fce11d0c8ca3.png">

If you go to that particular dataset on the IPT (https://ipt.inbo.be/resource?r=inboveg-turnhout-ponds-events#dataRecords) you'll see that the number of occurrences is also 1553.

Both should show the number of **Occurrences**.

**Comment by peterdesmet** [comment]
Note: the same occurs for checklist datasets: the IPT count = number of taxa (66) vs GBIF count = number of occurrences (0). Here you would want to compare the number of taxa of course, which is [66](https://www.gbif.org/species/search?dataset_key=72aa797d-42a4-4176-9e19-5b3ddd551b79&origin=SOURCE&advanced=1) for both.

<img width="955" alt="odonata" src="https://user-images.githubusercontent.com/600993/35726188-3f1e661e-0804-11e8-9393-6c5d4462fff2.png">

**Comment by MortenHofft** [comment]
Yes I see that. Since occurrences is what we see drift and should do something about i will use occurrence count only. Apparently the IPT api use the field "records" differently depending on the dataset type. I wasn't aware of that. thank you!

**Comment by peterdesmet** [comment]
So management will also show occurrence (drift) for occ in Event or Taxon datasets?
