### ISSUE TITLE
force-delete-previous-crawls script is not working

### ISSUE THREAD

**Issue by jlegind** [gbif/management-tools#18]
The force delete script in /crap/util on prodcrawler1 is not working as expected.

Example:
./force-delete-previous-crawls 97c2f1b2-42f5-45ca-9248-adb4b53fe491

Yields a bunch of warnings and then just hangs without returning the process to the CLI (the deletion is not picked up in the RabbitMQ either):

Note: --dataset-key is provided so --report-output-path will be ignored and --display-report will be forced
INFO  [05-07 14:12:18,032+0200] [main] org.gbif.ws.security.GbifAuthService:  Initialising auth service with key gbif.hit
INFO  [05-07 14:12:18,164+0200] [main] org.gbif.ws.security.GbifAuthService:  Initialised appkey store with 1 keys
WARN  [05-07 14:12:18,398+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public org.gbif.api.model.occurrence.Occurrence org.gbif.occurrence.ws.client.OccurrenceWsClient.get(java.lang.Integer)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@149dd36b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,463+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public java.lang.Object org.gbif.registry.ws.client.BaseNetworkEntityClient.get(java.lang.Object)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,464+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public java.lang.Object org.gbif.registry.ws.client.BaseNetworkEntityClient.get(java.util.UUID)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,465+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public void org.gbif.registry.ws.client.BaseNetworkEntityClient.update(java.lang.Object)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,465+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public java.util.UUID org.gbif.registry.ws.client.BaseNetworkEntityClient.create(java.lang.Object)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,498+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public java.lang.Object org.gbif.registry.ws.client.BaseNetworkEntityClient.get(java.lang.Object)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,498+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public java.lang.Object org.gbif.registry.ws.client.BaseNetworkEntityClient.get(java.util.UUID)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,499+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public void org.gbif.registry.ws.client.BaseNetworkEntityClient.update(java.lang.Object)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,499+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public java.util.UUID org.gbif.registry.ws.client.BaseNetworkEntityClient.create(java.lang.Object)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,531+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public java.lang.Object org.gbif.registry.ws.client.BaseNetworkEntityClient.get(java.lang.Object)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,531+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public java.lang.Object org.gbif.registry.ws.client.BaseNetworkEntityClient.get(java.util.UUID)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,532+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public void org.gbif.registry.ws.client.BaseNetworkEntityClient.update(java.lang.Object)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,532+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public java.util.UUID org.gbif.registry.ws.client.BaseNetworkEntityClient.create(java.lang.Object)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,565+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public java.lang.Object org.gbif.registry.ws.client.BaseNetworkEntityClient.get(java.lang.Object)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,565+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public java.lang.Object org.gbif.registry.ws.client.BaseNetworkEntityClient.get(java.util.UUID)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,566+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public void org.gbif.registry.ws.client.BaseNetworkEntityClient.update(java.lang.Object)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,566+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public java.util.UUID org.gbif.registry.ws.client.BaseNetworkEntityClient.create(java.lang.Object)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,597+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public java.util.List org.gbif.registry.ws.client.DatasetSearchWsClient.suggest(org.gbif.api.model.common.search.SearchRequest)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,598+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public org.gbif.api.model.common.search.SearchResponse org.gbif.registry.ws.client.DatasetSearchWsClient.search(org.gbif.api.model.common.search.SearchRequest)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,610+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public java.lang.Object org.gbif.registry.ws.client.BaseNetworkEntityClient.get(java.lang.Object)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,611+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public java.lang.Object org.gbif.registry.ws.client.BaseNetworkEntityClient.get(java.util.UUID)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,611+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public void org.gbif.registry.ws.client.BaseNetworkEntityClient.update(java.lang.Object)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,612+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public java.util.UUID org.gbif.registry.ws.client.BaseNetworkEntityClient.create(java.lang.Object)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN  [05-07 14:12:18,636+0200] [main] com.google.inject.internal.ProxyFactory:  Method [public org.gbif.api.model.occurrence.Download org.gbif.registry.ws.client.OccurrenceDownloadWsClient.get(java.lang.String)] is synthetic and is being intercepted by [org.gbif.ws.client.interceptor.HttpErrorResponseInterceptor@5023bb8b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
INFO  [05-07 14:12:19,262+0200] [main] org.gbif.registry.ws.client.DatasetWsClient$$EnhancerByGuice$$e90c3745:  Creating new DatasetWsClient$$EnhancerByGuice$$e90c3745 using webservices at https://api.gbif.org/v1/dataset
INFO  [05-07 14:12:19,391+0200] [main] org.gbif.occurrence.ws.client.OccurrenceWsSearchClient$$EnhancerByGuice$$311e11d3:  Creating new OccurrenceWsSearchClient$$EnhancerByGuice$$311e11d3 using webservices at http://api.gbif.org/v1/occurrence
INFO  [05-07 14:12:19,409+0200] [main] org.gbif.common.messaging.DefaultMessagePublisher:  Connecting to AMQP broker mutator:mutator@mq.gbif.org:5672 /prod
INFO  [05-07 14:12:19,531+0200] [main] org.gbif.registry.ws.client.DatasetWsClient$$EnhancerByGuice$$e90c3745:  Creating new DatasetWsClient$$EnhancerByGuice$$e90c3745 using webservices at https://api.gbif.org/v1/dataset
INFO  [05-07 14:12:19,629+0200] [main] org.apache.hive.jdbc.Utils: 97c2f1b2-42f5-45ca-9248-adb4b53fe491 Supplied authorities: c5hive2.gbif.org:10000
INFO  [05-07 14:12:19,630+0200] [main] org.apache.hive.jdbc.Utils: 97c2f1b2-42f5-45ca-9248-adb4b53fe491 Resolved authority: c5hive2.gbif.org:10000

**Comment by MattBlissett** [comment]
http://c5yarn.gbif.org:8088/cluster/apps/RUNNING

It runs a map-reduce job, which can take several minutes. I've started it (exactly your command), let's see if it works.

**Comment by MattBlissett** [comment]
Command output after about 2 minutes:

```
{
  "datasetKey" : "97c2f1b2-42f5-45ca-9248-adb4b53fe491",
  "lastCrawlId" : 31,
  "lastCrawlCount" : 1291,
  "recordCount" : 2653,
  "lastCrawlFragmentEmittedCount" : 1291,
  "finishReason" : "NORMAL",
  "processStateOccurrence" : "FINISHED",
  "crawlInfo" : [ {
    "crawlId" : 1,
    "count" : 71
  }, {
    "crawlId" : 8,
    "count" : 1291
  }, {
    "crawlId" : 31,
    "count" : 1291
  } ],
  "percentagePreviousCrawls" : 51.33810780248775
}
```
