### ISSUE TITLE
IPT synchronisation state

### ISSUE THREAD

**Issue by timrobertson100** [gbif/management-tools#2]
IPT installations expose [an inventory](http://labs.gbif.org:7007/inventory/dataset) of their registered resources.

This console should allow the user to enter the base URL for an IPT (or provide one in a link) that calls the inventory, and then for each dataset lists the status in GBIF coloured e.g. green for fully sync'ed or red for those needing attention.  An example of how this might look, and what is useful to display is [on the VertNet sync status console](http://timrobertson100.github.io/vertnet-gbif-diagnostic/target/index.html).  Please note that is not using the IPT URL but the concept is the same.

Please be aware of [this IPT issue](https://github.com/gbif/ipt/issues/1344) which means the inventory fails for IPTs < v2.5 which use extensions.  It would be helpful if the console reported to the user that "Due to IPT Bug 1344 (link) this is not possible.  Please upgrade to the latest IPT to use this functionality".

**Comment by MortenHofft** [comment]
No CORS
Missing `'Access-Control-Allow-Origin': *` in the IPT so the API cannot be used as is.

**Comment by MortenHofft** [comment]
This is largely implemented but is using mock data (due to above mentioned issue)

**Comment by timrobertson100** [comment]
Is a portal16 proxy feasible? Will be many months before IPTs roll out a change

**Comment by MortenHofft** [comment]
I can add it there. There isn't any more obvious places. registry fx?

**Comment by MortenHofft** [comment]
missing

* [x] proxy
* [x] test for 404
* [x] test for the above described IPT issue
* [ ] what other source archive types exists? currently only shows link if dwca
* [x] write description for landing page and about page
* [x] remember previous selections to ease use for returning users

**Comment by MortenHofft** [comment]
Clsoing this. @timrobertson100 if other things than darwin core will be provided, please let me know. See above missing checkbox
