### ISSUE TITLE
pipelines ingestion monitor broken

### ISSUE THREAD

**Issue by MortenHofft** [gbif/management-tools#20]
I see that the management tools got a new menu item. But it also seem to be broke (has CORS errors in the logs). Since this is a public website I suggest that we remove it and we document what you would like it to do once the APIs are in place. Then perhaps we can discuss how to go about it? And @muttcg can implement it, or I can or a contractor.

**Comment by MattBlissett** [comment]
Replaced by https://registry.gbif.org/monitoring/running-ingestions
