### ISSUE TITLE
Overcrawl monitor

### ISSUE THREAD

**Issue by timrobertson100** [gbif/management-tools#3]
It is the case that sometimes occurrence data is removed from a dataset by the provider and needs deleted in GBIF.org index.  Currently [the previous crawls manager CLI job](https://github.com/gbif/occurrence/blob/master/occurrence-cli/src/main/java/org/gbif/occurrence/cli/crawl/PreviousCrawlsManager.java) which runs daily only concerns itself with DwC-A and is rather defensive about deleting (by design).  The result is that records will exist with the latest `crawlID` while others will also hang around with previous crawl IDs.

To get an overview of this it would be useful to present a summary of "overcrawled" datasets.  We can focus on DwC-A only datasets for the first simple version and [the crawler API](https://crawler.gbif.org/dataset/overcrawled) service can provide the list of datasets.  Please state on the console this is produced each day.

An idea for displaying this is available on [this quick console](https://github.com/timrobertson100/overcrawl-console) - I found the bar chart useful to quickly spot things like completely duplicated datasets.

There are CLI tools to delete datasets, which need to be triggered by GBIFS staff today.  

I propose we start with DwC-A view only, and get this down to no overcrawled datasets.  This console can provide the overview status and the GBIFS staff will use the CLI tools to do the deletions.  

Future enhancements could include other protocols (although we might consider waiting for ABCD-A crawling support which will simplify that greatly) and the ability to trigger deletions from the console directly (which brings complexities around authentication and new APIs needed).  Those are out of scope for this ticket, and can be considered later.

**Comment by MortenHofft** [comment]
An initial version is now available. We can talk about what the about area should read and which fields from the response should show (all perhaps)
![screen shot 2017-12-01 at 12 14 46](https://user-images.githubusercontent.com/6759267/33480540-45078d48-d691-11e7-999a-b1524f00da03.png)

**Comment by MortenHofft** [comment]
I realise i don't understand what `percentagePreviousCrawls` is so I might well have displayed it in a meaningless way

**Comment by MortenHofft** [comment]
@timrobertson100 the response at https://crawler.gbif.org/dataset/overcrawled has changed format and only includes one item. It used to be an object with keys for each dataset. 

```
{
"datasetKey": "7f5260c2-f762-11e1-a439-00145eb45e9a",
"lastCrawlId": 12,
"lastCrawlCount": 207221,
"recordCount": 207906,
"lastCrawlFragmentEmittedCount": 207880,
"crawlInfo": [
{
"crawlId": 11,
"count": 685
},
{
"crawlId": 12,
"count": 207221
}
],
"percentagePreviousCrawls": 0.3294758208036324
}
```

**Comment by timrobertson100** [comment]
For info. 
This is a static file which is [surfaced as a web service](https://github.com/gbif/crawler/blob/master/crawler-ws/src/main/java/org/gbif/crawler/ws/OvercrawledResource.java#L25) and produced on a timer as [documented here](https://github.com/gbif/occurrence/blob/4cc8a1341349b78a5bd33acb63f711499820ded8/occurrence-cli/doc/PreviousCrawlManager.md).  At the time of writing the configuration has this start at 09:37 every day and the file does have a single entry.

I am not entirely sure why this has only 1 entry today but it should be noted that a race condition does exist.  The previous crawl job relies on the `occurrence_hdfs` table existing which can have a moment of being swapped in.

Running the following HQL now demonstrates that there are 423 at the time of writing.
```
select datasetKey, count(distinct crawlId) 
from prod_d.occurrence_hdfs
where protocol='DWC_ARCHIVE'
group by datasetkey
having count(distinct crawlid) > 1
```

While this remains a mystery I have reconfigured it to run at 11:45 which is a safer window given the timing of the `occurrence_hdfs` job build.  The file looks correct now.

**Comment by timrobertson100** [comment]
> I realise i don't understand what percentagePreviousCrawls is so I might well have displayed it in a meaningless way

I believe the `percentagePreviousCrawls` represents the total percentage of records that would be deleted if all but the records for the last crawl were deleted.  Currently the GBIF [previous crawl manager will auto delete things up to 30%](https://github.com/gbif/gbif-configuration/blob/59f3e1c99d3f7ba133111f6e3734d63c49adef87/cli/prod/config/occurrence/previous-crawls-manager.yaml#L24)

**Comment by timrobertson100** [comment]
Additionally, I have found that [the limit](https://github.com/gbif/occurrence/blob/master/occurrence-cli/src/main/java/org/gbif/occurrence/cli/crawl/PreviousCrawlsManager.java#L135) was limiting to 10 datasets to consider for deletion, and would always run on the same 10 datasets.  This has been increased to 1000 now, so I expect the next run should delete more.
