### ISSUE TITLE
Dataset crawl history

### ISSUE THREAD

**Issue by timrobertson100** [gbif/management-tools#5]
For any dataset (either looked up on the site, or linked by UUID) a tabular view of the crawl history would be useful.  The view would show information from [this API example call](http://api.gbif.org/v1/dataset/2d59e5db-57ad-41ff-97d6-11f5fb264527/process) and would show only the timestamp (note: [this issue](https://github.com/gbif/registry/issues/33)) along with the records added (`rawOccurrencesPersistedNew`), records updates (`rawOccurrencesPersistedUpdated`) and records unchanged (`rawOccurrencesPersistedUnchanged`) and the crawl duration (e.g. 14 minutes) if possible.

Note: we only care to show the `raw*` values as the goal is to show what has been changed on the publisher side, to get insight into whether the dataset is growing or changing.  GBIF regularly reprocess the raw records when e.g. changes to the interpretation code is deployed.

This would be useful to link to from the dataset pages on GBIF.org.

I suggest it is only worthwhile showing crawls that finished successfully and stating as such.  It might be of use to have a "show all" which would add more rows to the table, with a status column or so.  However, we often kill crawling and restart so it pollutes the view and I'd suggest not surfacing that as the default view - the default helps folk understand the growth in the dataset.

**Comment by MortenHofft** [comment]
Implemented but has a placeholder description and could use another pair of eyes for testing

**Comment by MortenHofft** [comment]
missing

* [x] add 404 testing
* [x] test for deleted dataset
* [ ] add pagination option? If so then the API need to support only returning NORMAL crawls else a page could be empty
* [x] prose describing what it is
* [x] remember previous selections to ease use for returning users

**Comment by MortenHofft** [comment]
closing this as no one have had any comments on it in testing
