### ISSUE TITLE
Surface the prod-crawl kibana logs

### ISSUE THREAD

**Issue by timrobertson100** [gbif/management-tools#6]
We wish for the production crawl logs in Kibana to be visible and searchable publicly.

E.g. http://elk.gbif.org:5601/app/kibana#/discover?_a=(columns:!(_source),filters:!(('$$hashKey':'object:78','$state':(store:appState),meta:(alias:!n,disabled:!f,index:'prod-crawl-*',key:datasetKey,negate:!f,value:'6ce9819a-d82b-41e1-9059-0dd201f15993'),query:(match:(datasetKey:(query:'6ce9819a-d82b-41e1-9059-0dd201f15993',type:phrase))))),index:'prod-crawl-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'*')),sort:!('@timestamp',desc))&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))

This can be behind authentication if necessary but ideally not.  It could be a fresh kibana on the web, or perhaps the existing can provide a dashboard?

It might be embedded in the management-tools page (e.g. iframe or similar) or simply linked to from various places such as the running crawls overview.

**Comment by MattBlissett** [comment]
This was done a month or so ago.
