### ISSUE TITLE
Minor: Add pill on crawl history if count is off

### ISSUE THREAD

**Issue by timrobertson100** [gbif/management-tools#7]
on the [crawl history](http://localhost:3000/crawl-history?uuid=7e380070-f762-11e1-a439-00145eb45e9a) it would be useful to colour "a pill" at the top to indicate if the numbers are suspicious or not - i.e. the same as done of the GBIF dataset page.

**Comment by MortenHofft** [comment]
I actually did here https://github.com/gbif/management-tools/blob/master/src/app/routes/crawlHistory/CrawlHistory.html#L51
but removed it as I wanted us to agree on what counts as suspicious.

Should i look to `fragmentsEmitted` or `fragmentsReceived` and should it have `"finishReason": "NORMAL"` ?

```
{
...
  "startedCrawling": "2016-06-20T22:00:00.000+0000",
  "finishedCrawling": "2016-06-20T22:00:00.000+0000",
  "finishReason": "NORMAL",
  "processStateOccurrence": "RUNNING",
  "processStateChecklist": "EMPTY",
  "pagesCrawled": 3860,
  "pagesFragmentedSuccessful": 3844,
  "pagesFragmentedError": 16,
  "fragmentsEmitted": 3829468,
  "fragmentsReceived": 3829468,
  "rawOccurrencesPersistedNew": 0,
  "rawOccurrencesPersistedUpdated": 0,
  "rawOccurrencesPersistedUnchanged": 3829468,
  "rawOccurrencesPersistedError": 0,
  "fragmentsProcessed": 3829468,
  "verbatimOccurrencesPersistedSuccessful": 0,
  "verbatimOccurrencesPersistedError": 0,
  "interpretedOccurrencesPersistedSuccessful": 0,
  "interpretedOccurrencesPersistedError": 0
}
```

and is it correct that fragmentRecieved == new+unchanged+updated+errors?

![screen shot 2017-12-04 at 11 34 42](https://user-images.githubusercontent.com/6759267/33548370-3f738258-d8e7-11e7-9e29-c25874b871c1.png)

**Comment by MortenHofft** [comment]
logic ended up being : if darwin core archive and finished normal and recieved != occ index count
