### ISSUE TITLE
Publisher on overcrawl monitor

### ISSUE THREAD

**Issue by timrobertson100** [gbif/management-tools#8]
Jan says it would be very useful to have publisher (or key) and have it sortable so you can see if they are coming from a single publisher.  Seems reasonable since publishers are known to change ID strategy for many datasets in one go.

**Comment by MortenHofft** [comment]
makes sense. will you add it in the response or should i do the lookups client side? I guess it would be a lookup for the dataset and then another one for the publisher. with the current list length (500 dataset?) that would be ≈1000 (perhaps there are many duplicates) calls. The page will feel slower, but i guess that is okay for this one.

**Comment by MortenHofft** [comment]
From conversation: for now the decision is to implement this in the API. once that is done adding the extra column in trivial

**Comment by ManonGros** [comment]
It would be also really great if this could also allow to group the datasets by hosting installation.

**Comment by MattBlissett** [comment]
Overcrawl monitor is obsolete.
